/-
 * GUTOE — Textbook OS/Wightman Objects on Wilson Lane
 * Copyright (C) 2026  Riff Labs
 * AGPL-3.0-or-later
 *
 * GRAND-320:
 *   Provide concrete functional-analytic objects (quotient Hilbert carrier,
 *   transfer semigroup, positivity properties) for the hard-mode constructive
 *   Yang-Mills lane.
 *
 * No `sorry`.
 -/

import Mathlib
import Gutoe.YangMillsConstructiveHardMode

noncomputable section

namespace Gutoe.YangMillsOSTextbook

open scoped BigOperators
open Gutoe.YangMillsConstructiveQFT
open Gutoe.YangMillsConstructiveHardMode
open Gutoe.YangMillsWilsonBridge
open Gutoe.YangMillsWilsonEquivalence

/-- Concrete Euclidean test-function space used in the finite transfer lane. -/
abbrev EuclideanTestSpace : Type := Fin 3 → ℝ

/-- Dot product on `Fin 3 → ℝ`. -/
def dot3 (u v : EuclideanTestSpace) : ℝ :=
  u 0 * v 0 + u 1 * v 1 + u 2 * v 2

/-- Dot product of a vector with itself is nonnegative. -/
theorem dot3_self_nonneg (u : EuclideanTestSpace) : 0 ≤ dot3 u u := by
  unfold dot3
  nlinarith [sq_nonneg (u 0), sq_nonneg (u 1), sq_nonneg (u 2)]

/-- Kernel image representative used for the OS quotient relation. -/
def kernelImage (K : Matrix (Fin 3) (Fin 3) ℝ) (f : EuclideanTestSpace) :
    EuclideanTestSpace :=
  K.mulVec f

/-- OS quotient relation: vectors are equivalent if they have equal kernel image. -/
def OSRel (K : Matrix (Fin 3) (Fin 3) ℝ) (f g : EuclideanTestSpace) : Prop :=
  kernelImage K f = kernelImage K g

theorem OSRel_refl (K : Matrix (Fin 3) (Fin 3) ℝ) :
    Reflexive (OSRel K) := by
  intro f
  rfl

theorem OSRel_symm (K : Matrix (Fin 3) (Fin 3) ℝ) :
    Symmetric (OSRel K) := by
  intro f g h
  simpa [OSRel] using h.symm

theorem OSRel_trans (K : Matrix (Fin 3) (Fin 3) ℝ) :
    Transitive (OSRel K) := by
  intro f g h hfg hgh
  exact Eq.trans hfg hgh

/-- Setoid generated by `OSRel`. -/
def osSetoid (K : Matrix (Fin 3) (Fin 3) ℝ) : Setoid EuclideanTestSpace where
  r := OSRel K
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro f
      exact OSRel_refl K f
    · intro f g h
      exact OSRel_symm K h
    · intro f g h hfg hgh
      exact OSRel_trans K hfg hgh

/-- Concrete OS quotient carrier (finite transfer lane). -/
abbrev OSHilbertQuot (K : Matrix (Fin 3) (Fin 3) ℝ) : Type :=
  Quotient (osSetoid K)

/-- Representative-level OS inner product candidate. -/
def osInnerRep (K : Matrix (Fin 3) (Fin 3) ℝ)
    (f g : EuclideanTestSpace) : ℝ :=
  dot3 (kernelImage K f) (kernelImage K g)

theorem osInnerRep_congr
    (K : Matrix (Fin 3) (Fin 3) ℝ)
    {f f' g g' : EuclideanTestSpace}
    (hf : OSRel K f f')
    (hg : OSRel K g g') :
    osInnerRep K f g = osInnerRep K f' g' := by
  unfold osInnerRep OSRel kernelImage at *
  simp [hf, hg]

/-- Quotient-level OS inner product candidate. -/
def osInner (K : Matrix (Fin 3) (Fin 3) ℝ) :
    OSHilbertQuot K → OSHilbertQuot K → ℝ :=
  Quotient.lift₂
    (fun f g => osInnerRep K f g)
    (by
      intro f f' g g' hf hg
      exact osInnerRep_congr K hf hg)

/-- Nonnegativity on the quotient carrier. -/
theorem osInner_self_nonneg
    (K : Matrix (Fin 3) (Fin 3) ℝ)
    (x : OSHilbertQuot K) :
    0 ≤ osInner K x x := by
  refine Quotient.inductionOn x ?_
  intro f
  change 0 ≤ osInnerRep K f f
  unfold osInnerRep
  exact dot3_self_nonneg (kernelImage K f)

/-- One-step transfer map on the OS quotient carrier. -/
def osTransfer (K : Matrix (Fin 3) (Fin 3) ℝ) :
    OSHilbertQuot K → OSHilbertQuot K :=
  Quotient.map
    (fun f => kernelImage K f)
    (by
      intro f g hfg
      change OSRel K (kernelImage K f) (kernelImage K g)
      exact congrArg (fun v => K.mulVec v) hfg)

/-- Discrete semigroup generated by the one-step transfer map. -/
def osSemigroup (K : Matrix (Fin 3) (Fin 3) ℝ) :
    ℕ → OSHilbertQuot K → OSHilbertQuot K
  | 0 => fun x => x
  | n + 1 => fun x => osTransfer K (osSemigroup K n x)

/-- Semigroup composition law on the quotient carrier. -/
theorem osSemigroup_add
    (K : Matrix (Fin 3) (Fin 3) ℝ) :
    ∀ m n x,
      osSemigroup K (m + n) x =
        osSemigroup K m (osSemigroup K n x) := by
  intro m
  induction m with
  | zero =>
      intro n x
      simp [osSemigroup]
  | succ m ih =>
      intro n x
      simpa [osSemigroup, Nat.succ_add, ih]

/-- Wilson kernel at refinement step `n`. -/
def wilsonKernelAt
    (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) :
    Matrix (Fin 3) (Fin 3) ℝ :=
  wilsonKernel 1 (centerPlaquetteActionSchedule W alpha n)

/-- Row-stochasticity witness at step `n`. -/
def osRowStochasticAt (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) : Prop :=
  ∀ i : Fin 3, (∑ j : Fin 3, wilsonKernelAt W alpha n i j) = 1

/-- Strict positivity witness at step `n`. -/
def osKernelPositiveAt (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) : Prop :=
  ∀ i j : Fin 3, 0 < wilsonKernelAt W alpha n i j

theorem os_row_stochastic_at
    (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) :
    osRowStochasticAt W alpha n := by
  intro i
  exact wilson_kernel_row_sum_one 1 (centerPlaquetteActionSchedule W alpha n) i

theorem os_kernel_positive_at
    (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) :
    osKernelPositiveAt W alpha n := by
  intro i j
  unfold wilsonKernelAt wilsonKernel normalizedKernelFromWeights
  have hnum : 0 < wilsonWeight 1 (centerPlaquetteActionSchedule W alpha n) i j := by
    exact wilson_weight_pos 1 (centerPlaquetteActionSchedule W alpha n) i j
  have hden : 0 < (∑ k : Fin 3, wilsonWeight 1 (centerPlaquetteActionSchedule W alpha n) i k) := by
    have hpart : 0 < wilsonRowPartition 1 (centerPlaquetteActionSchedule W alpha n) i :=
      wilson_row_partition_pos 1 (centerPlaquetteActionSchedule W alpha n) i
    simpa [wilsonRowPartition] using hpart
  exact div_pos hnum hden

/-- Concrete OS reconstruction package at step `n`. -/
def osReconstructionTextbookAt
    (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) : Prop :=
  let K := wilsonKernelAt W alpha n
  osRowStochasticAt W alpha n ∧
  osKernelPositiveAt W alpha n ∧
  Nonempty (OSHilbertQuot K) ∧
  (∀ x : OSHilbertQuot K, 0 ≤ osInner K x x) ∧
  (∀ m k : ℕ, ∀ x : OSHilbertQuot K,
    osSemigroup K (m + k) x = osSemigroup K m (osSemigroup K k x))

/-- Stepwise textbook OS reconstruction package is available unconditionally on
the finite Wilson lane. -/
theorem os_reconstruction_textbook_at
    (W : WilsonZ3Action) (alpha : ℝ) (n : ℕ) :
    osReconstructionTextbookAt W alpha n := by
  refine ⟨os_row_stochastic_at W alpha n, os_kernel_positive_at W alpha n, ?_, ?_, ?_⟩
  · exact ⟨Quotient.mk _ (fun _ => 0)⟩
  · intro x
    exact osInner_self_nonneg (wilsonKernelAt W alpha n) x
  · intro m k x
    exact osSemigroup_add (wilsonKernelAt W alpha n) m k x

/-- Concrete OS reconstruction milestone for hard-mode model follows from the
textbook package at each refinement step. -/
theorem hard_mode_os_reconstruction_from_textbook
    (W : WilsonZ3Action) (alpha : ℝ) :
    (hardModeModel W (fun _ => 1) alpha).milestones.osReconstruction := by
  refine ⟨wilsonKernelAt W alpha, ?_, ?_, ?_⟩
  · intro n
    rfl
  · intro n i
    exact (os_row_stochastic_at W alpha n) i
  · intro n i j
    exact (os_kernel_positive_at W alpha n) i j

/-- Concrete Hamiltonian value at refinement step `n`, threaded directly from
the hard-mode gap sequence. -/
def osHamiltonianAt
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (n : ℕ) : ℝ :=
  hardModeGapSeq W a_t alpha n

/-- Spectral condition (lower-spectrum nonnegativity) in the hard-mode lane. -/
def osSpectralCondition
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ) : Prop :=
  ∀ n, 0 ≤ osHamiltonianAt W a_t alpha n

/-- Concrete two-point Wightman candidate from the stepwise Hamiltonian. -/
def wightmanAt
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (n : ℕ) : ℕ → ℝ :=
  fun t => Real.exp (-(osHamiltonianAt W a_t alpha n) * (t : ℝ))

theorem wightmanAt_nonneg
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (n t : ℕ) :
    0 ≤ wightmanAt W a_t alpha n t := by
  unfold wightmanAt
  exact le_of_lt (Real.exp_pos _)

theorem wightmanAt_semigroup_time
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (n t s : ℕ) :
    wightmanAt W a_t alpha n (t + s) =
      wightmanAt W a_t alpha n t * wightmanAt W a_t alpha n s := by
  unfold wightmanAt
  have hcast : ((t + s : ℕ) : ℝ) = (t : ℝ) + (s : ℝ) := by
    exact_mod_cast Nat.cast_add t s
  calc
    Real.exp (-(osHamiltonianAt W a_t alpha n) * ((t + s : ℕ) : ℝ))
        = Real.exp (-(osHamiltonianAt W a_t alpha n) * ((t : ℝ) + (s : ℝ))) := by
            rw [hcast]
    _ = Real.exp ((-(osHamiltonianAt W a_t alpha n) * (t : ℝ)) +
        (-(osHamiltonianAt W a_t alpha n) * (s : ℝ))) := by ring_nf
    _ = Real.exp (-(osHamiltonianAt W a_t alpha n) * (t : ℝ)) *
        Real.exp (-(osHamiltonianAt W a_t alpha n) * (s : ℝ)) := by
            rw [Real.exp_add]

/-- Full concrete textbook package at a fixed refinement step. -/
structure OSTextbookPackageAt
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (n : ℕ) where
  K : Matrix (Fin 3) (Fin 3) ℝ
  K_eq : K = wilsonKernelAt W alpha n
  rowStochastic : ∀ i : Fin 3, (∑ j : Fin 3, K i j) = 1
  entryPositive : ∀ i j : Fin 3, 0 < K i j
  quotientNonempty : Nonempty (OSHilbertQuot K)
  innerSelfNonneg : ∀ x : OSHilbertQuot K, 0 ≤ osInner K x x
  semigroupLaw :
    ∀ m k : ℕ, ∀ x : OSHilbertQuot K,
      osSemigroup K (m + k) x = osSemigroup K m (osSemigroup K k x)
  hamiltonian : ℝ
  hamiltonian_eq : hamiltonian = osHamiltonianAt W a_t alpha n
  spectralNonneg : 0 ≤ hamiltonian
  wightman : ℕ → ℝ
  wightman_def : ∀ t, wightman t = Real.exp (-hamiltonian * (t : ℝ))
  wightman_nonneg : ∀ t, 0 ≤ wightman t
  wightman_semigroup_time :
    ∀ t s : ℕ, wightman (t + s) = wightman t * wightman s

/-- Domain assumptions produce a concrete textbook package at each refinement
step: OS quotient, semigroup/Hamiltonian, spectral condition, and Wightman
candidate are all explicit objects. -/
def os_textbook_package_at_of_domain
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (hDom : WilsonEquivalenceDomain a_t alpha)
    (n : ℕ) :
    OSTextbookPackageAt W a_t alpha n := by
  refine
    { K := wilsonKernelAt W alpha n
      K_eq := rfl
      rowStochastic := os_row_stochastic_at W alpha n
      entryPositive := os_kernel_positive_at W alpha n
      quotientNonempty := ⟨Quotient.mk _ (fun _ => 0)⟩
      innerSelfNonneg := osInner_self_nonneg (wilsonKernelAt W alpha n)
      semigroupLaw := osSemigroup_add (wilsonKernelAt W alpha n)
      hamiltonian := osHamiltonianAt W a_t alpha n
      hamiltonian_eq := rfl
      spectralNonneg := ?_
      wightman := wightmanAt W a_t alpha n
      wightman_def := ?_
      wightman_nonneg := ?_
      wightman_semigroup_time := ?_ }
  · rcases c3_gap_correspondence_of_domain W a_t alpha hDom with ⟨c, hcPos, hcLe⟩
    have hlt : 0 < osHamiltonianAt W a_t alpha n := by
      exact lt_of_lt_of_le hcPos (by simpa [osHamiltonianAt, hardModeGapSeq, hardModeEpsSeq] using hcLe n)
    exact le_of_lt hlt
  · intro t
    rfl
  · intro t
    exact wightmanAt_nonneg W a_t alpha n t
  · intro t s
    exact wightmanAt_semigroup_time W a_t alpha n t s

/-- Spectral condition is threaded from domain assumptions on the full
refinement schedule. -/
theorem os_spectral_condition_of_domain
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (hDom : WilsonEquivalenceDomain a_t alpha) :
    osSpectralCondition W a_t alpha := by
  intro n
  let P := os_textbook_package_at_of_domain W a_t alpha hDom n
  have hEq : P.hamiltonian = osHamiltonianAt W a_t alpha n := P.hamiltonian_eq
  have hNonneg : 0 ≤ P.hamiltonian := P.spectralNonneg
  simpa [hEq] using hNonneg

/-- Hard-mode constructive-target closure together with textbook OS objects and
Wightman witness under Wilson-equivalence domain assumptions. -/
theorem constructive_targets_and_textbook_objects_of_domain
    (W : WilsonZ3Action)
    (a_t : ℕ → ℝ)
    (alpha : ℝ)
    (hDom : WilsonEquivalenceDomain a_t alpha) :
    constructiveTargetsSatisfied (hardModeModel W a_t alpha) ∧
    (∀ n, osReconstructionTextbookAt W alpha n) ∧
    hardModeWightmanCompatibility W a_t alpha ∧
    osSpectralCondition W a_t alpha ∧
    (∀ n, Nonempty (OSTextbookPackageAt W a_t alpha n)) := by
  refine ⟨constructive_targets_satisfied_of_hard_mode_domain W a_t alpha hDom, ?_, ?_, ?_, ?_⟩
  · intro n
    exact os_reconstruction_textbook_at W alpha n
  · exact hard_mode_wightman_compatibility_of_domain W a_t alpha hDom
  · exact os_spectral_condition_of_domain W a_t alpha hDom
  · intro n
    exact ⟨os_textbook_package_at_of_domain W a_t alpha hDom n⟩

end Gutoe.YangMillsOSTextbook
