import Lake
open Lake DSL

package gutoe

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib Gutoe where
  roots := #[`Gutoe.Basic, `Gutoe.HexStates, `Gutoe.GateProperties, `Gutoe.RealGates,
             `Gutoe.ParticleFormation, `Gutoe.DispersionRelation, `Gutoe.RailSpace,
             `Gutoe.VoidRearFace,
             `Gutoe.Spacetime, `Gutoe.HawkingCorrection, `Gutoe.FTLGeometry, `Gutoe.CTCLegality, `Gutoe.CTCParadoxOtherwise, `Gutoe.CliffordStructure,
             `Gutoe.ProjectionFibers,
             `Gutoe.RecursiveZ3Tower,
             `Gutoe.RecursiveNavigationNoTranslation,
             `Gutoe.CreationLanes,
             `Gutoe.CTCPathAEffectiveArrival,
             `Gutoe.CTCPathAQClosure,
             `Gutoe.EvenSubalgebraSuppression,
             `Gutoe.OverdeterminedTopologyRatios,
             `Gutoe.FiberChannelCapacity,
             `Gutoe.ContainmentScope,
             `Gutoe.TopologicalAccessControllability,
             `Gutoe.TopologicalAccessOperator,
             `Gutoe.CTCDoorEnergyBookkeeping,
             `Gutoe.CTCClosedLoopTemporalLoan,
             `Gutoe.CTCRetroRetryClosure,
             `Gutoe.CTCBootstrapFixedPoint,
             `Gutoe.DynamicTopologyCreation,
             `Gutoe.NonConjugationQuotient,
             `Gutoe.TopologicalDefectBundle,
             `Gutoe.VacuumEnergyBounds,
             `Gutoe.FTLExhaustion,
             `Gutoe.FTLRearFaceBridge,
             `Gutoe.FTLFrameCTCBridge,
             `Gutoe.BaryonPhysics, `Gutoe.HexFermions, `Gutoe.DynamicsProperties,
             `Gutoe.TopologyForces, `Gutoe.Conjectures, `Gutoe.HydrogenFormation,
             `Gutoe.FineStructure, `Gutoe.MassSpectrum, `Gutoe.DimensionalStructure,
             `Gutoe.Z3Uniqueness, `Gutoe.BellInequality, `Gutoe.ThreeGenerations,
             `Gutoe.KoideMasses, `Gutoe.LeptonMass, `Gutoe.PerturbativeSymmetry,
             `Gutoe.FlavorMixing,
             `Gutoe.TriangulatedConstants,
             `Gutoe.TriangulatedTermProvenance,
             `Gutoe.TriangulatedClosureUniqueness,
             `Gutoe.TriangulatedGrammarUniverse,
             `Gutoe.FiveLockClosure,
             `Gutoe.MultiplicativeTriangulation,
             `Gutoe.FCNCSuppression,
             `Gutoe.MuonG2,
             `Gutoe.Homochirality,
             `Gutoe.ProtonSpin,
             `Gutoe.NuclearFirstPrinciples,
             `Gutoe.FewBodyQM,
             `Gutoe.QuarkNeutrinoRatios,
             `Gutoe.SignatureUniqueness, `Gutoe.LatticeGeometry, `Gutoe.InstantonMass,
             `Gutoe.HolonomyGroup,
             `Gutoe.Z3ForcedStructure,
             `Gutoe.GaugeGroupSU2, `Gutoe.GaugeGroupSU3, `Gutoe.GaugeGroupSM,
             `Gutoe.GaugeConstants, `Gutoe.Chirality, `Gutoe.ContinuumLimit,
             `Gutoe.LorentzInvariance, `Gutoe.GrandMasterTheorem,
             `Gutoe.GravityMetric,
             `Gutoe.SingularityResolution,
             `Gutoe.EinsteinFromLattice,
             `Gutoe.KerrGeometry,
             `Gutoe.KerrCameraStability,
             `Gutoe.KerrTracerEquations,
             `Gutoe.KerrReferenceFrame,
             `Gutoe.Geodesic3DProjection,
             `Gutoe.SynchrotronGRMHD,
             `Gutoe.SynchrotronTransfer,
             `Gutoe.StrongCP,
             `Gutoe.StrongCPPathIntegral,
             `Gutoe.StrongCPVacuum,
             `Gutoe.StrongCPEmergence,
             `Gutoe.StrongCPGeneralCases,
             `Gutoe.ChiralSymmetryBreaking,
             `Gutoe.CoulombCorrection,
             `Gutoe.BlackHoleInfoParadox,
             `Gutoe.LatticeDiffraction,
             `Gutoe.YangMillsContinuumLimitKolmogorov,
             `Gutoe.Leptogenesis,
             `Gutoe.SMatrix,
             `Gutoe.SMQCDUnification,
             `Gutoe.EWSBHiggs,
             `Gutoe.CosmologicalConstant,
             `Gutoe.Inflation,
             `Gutoe.Baryogenesis,
             `Gutoe.BBN,
             `Gutoe.DarkMatterSector,
             `Gutoe.ChemicalThermodynamics,
             `Gutoe.CrystalStructureWeights,
             `Gutoe.CrystalCoefficientClosure,
             `Gutoe.IonizationRelaxationClosure,
             `Gutoe.ThermalEntropyClosure,
             `Gutoe.EverydayExtremes,
             `Gutoe.AbiogenesisThreshold,
             `Gutoe.LifeProgressionEntropy,
             `Gutoe.RTSCAdmissibility,
             `Gutoe.RTSCWitnessClosure,
             `Gutoe.RTSCIsotopeStability,
             `Gutoe.AntimatterProduction,
             `Gutoe.StellarFusion,
             `Gutoe.FalsifiabilityCatalog,
             `Gutoe.AsymptoticFreedomEntropy,
             `Gutoe.YangMillsMassGap,
             `Gutoe.YangMillsContinuumSurvival,
             `Gutoe.YangMillsConstructiveQFT,
             `Gutoe.YangMillsConstructiveHardMode,
             `Gutoe.YangMillsContinuumLimit,
             `Gutoe.YangMillsOSTextbook,
             `Gutoe.YangMillsOSCompletion,
             `Gutoe.YangMillsOSEndToEnd,
             `Gutoe.YangMillsGaugeScope,
             `Gutoe.YangMillsStructuralGap,
             `Gutoe.YangMillsFullStateLift,
             `Gutoe.YangMillsWilsonBridge,
             `Gutoe.YangMillsWilsonEquivalence,
             `Gutoe.HaarBridgeScaffold,
             `Gutoe.HaarMeasureHooks,
             `Gutoe.HaarExpectationDecomposition,
             `Gutoe.HaarFiberCollapse,
             `Gutoe.StrongCouplingCInfBridge,
             `Gutoe.ElectronScaleTransduction,
             `Gutoe.HadronTransduction,
             `Gutoe.SM.Rep,
             `Gutoe.SM.Anomalies,
             `Gutoe.SM.HyperchargeBridge,
             `Gutoe.SM.Closure,
             `Gutoe.LambdaQG,
             `Gutoe.RiemannCore,
             `Gutoe.RiemannSelfAdjoint,
             `Gutoe.RiemannBridge,
             `Gutoe.RiemannCounting,
             `Gutoe.RiemannLayer2Identity,
             `Gutoe.RiemannFiniteXiModel,
             `Gutoe.RiemannLimitBridge,
             `Gutoe.RiemannConvergenceTransfer,
             `Gutoe.RiemannFinalTarget,
             `Gutoe.RiemannRHClosure]

lean_exe kerr_ref_frame where
  root := `Gutoe.KerrReferenceFrameGen
